//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_HG_new_order
    {
        public int order_ { get; set; }
        public string openid_ { get; set; }
        public string name_ { get; set; }
        public string tel_ { get; set; }
        public string sex_ { get; set; }
        public string weixin_name { get; set; }
        public string pick_many { get; set; }
        public string type_ { get; set; }
        public string time_ { get; set; }
        public string pick_day { get; set; }
        public string adress { get; set; }
        public string order_dd { get; set; }
        public string Fw_name { get; set; }
        public string Fw_zt { get; set; }
        public string order_from { get; set; }
        public string str_1 { get; set; }
        public string str_2 { get; set; }
        public string str_3 { get; set; }
        public string total { get; set; }
        public string strat_time { get; set; }
        public string Delet_ { get; set; }
        public string end_time { get; set; }
    }
}
