//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_HG_GL
    {
        public int G_number { get; set; }
        public string G_sex { get; set; }
        public string G_adress { get; set; }
        public string G_diqu { get; set; }
        public string G_tel { get; set; }
        public string QQ { get; set; }
        public string Weixin { get; set; }
        public string G_age { get; set; }
        public string G_wid { get; set; }
        public string G_name { get; set; }
        public string Adress { get; set; }
    }
}
