//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_HG_HG
    {
        public int Hg_number { get; set; }
        public string Hg_name { get; set; }
        public string Hg_sex { get; set; }
        public string Hg_Degree { get; set; }
        public string Hg_Profile { get; set; }
        public string Hg_IDcard { get; set; }
        public Nullable<int> Hg_age { get; set; }
        public string Hg_st1 { get; set; }
        public string Hg_st2 { get; set; }
        public string Hg_st3 { get; set; }
        public Nullable<int> Hg_sum { get; set; }
        public Nullable<int> wid { get; set; }
        public string dengji { get; set; }
        public Nullable<int> Teacher_i { get; set; }
        public string Nation { get; set; }
        public string Marry { get; set; }
        public string Provice { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public string Weixin { get; set; }
        public string QQ { get; set; }
        public string Mony { get; set; }
        public string Headurl { get; set; }
        public string lg_pwd { get; set; }
        public string open_id_hg { get; set; }
        public string TeName { get; set; }
    }
}
