//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_HG_oreder
    {
        public int Oreder_id { get; set; }
        public string Openid { get; set; }
        public string Nursing_name { get; set; }
        public string Nursing_sex { get; set; }
        public string Nursing_tel { get; set; }
        public string Nursing_adress { get; set; }
        public string By_name { get; set; }
        public string By_sex { get; set; }
        public string By_care { get; set; }
        public string By_age { get; set; }
        public string By_adress { get; set; }
        public string HUli_type { get; set; }
        public string Start_time { get; set; }
        public string End_time { get; set; }
        public Nullable<int> Hg_number { get; set; }
        public string Status_order { get; set; }
        public string Rated_hg { get; set; }
        public Nullable<int> Rated_status { get; set; }
        public string Pay_type { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> wid { get; set; }
        public string Service_time { get; set; }
        public string Service_day { get; set; }
        public string Str_sm { get; set; }
        public string Hg_name { get; set; }
        public string Order_dd { get; set; }
    }
}
