//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card_BaseInfo
    {
        public int BaseInfoID { get; set; }
        public Nullable<int> wid { get; set; }
        public string Wx_Card_id { get; set; }
        public string Card_type { get; set; }
        public string logo_url { get; set; }
        public string brand_name { get; set; }
        public string title { get; set; }
        public string sub_title { get; set; }
        public string color { get; set; }
        public string notice { get; set; }
        public string service_phone { get; set; }
        public string source { get; set; }
        public string description { get; set; }
        public string use_limit { get; set; }
        public string get_limit { get; set; }
        public Nullable<bool> use_custom_code { get; set; }
        public Nullable<bool> bind_openid { get; set; }
        public Nullable<bool> can_share { get; set; }
        public string type { get; set; }
        public Nullable<bool> Paycell { get; set; }
        public string begin_timestamp { get; set; }
        public string end_timestamp_day { get; set; }
        public string quantity { get; set; }
        public Nullable<bool> can_give_friend { get; set; }
        public string url_name_type { get; set; }
        public string custom_url { get; set; }
        public string custom_url_name { get; set; }
        public string custom_url_sub_title { get; set; }
        public string promotion_url { get; set; }
        public string promotion_url_name { get; set; }
        public string least_cost { get; set; }
        public string reduce_cost { get; set; }
        public string default_detail { get; set; }
        public string Deal_detail { get; set; }
        public string discount { get; set; }
        public Nullable<bool> hexiao { get; set; }
    }
}
