//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_HG_admin> A_HG_admin { get; set; }
        public virtual DbSet<A_HG_FK> A_HG_FK { get; set; }
        public virtual DbSet<A_HG_GL> A_HG_GL { get; set; }
        public virtual DbSet<A_HG_HG> A_HG_HG { get; set; }
        public virtual DbSet<A_HG_new_order> A_HG_new_order { get; set; }
        public virtual DbSet<A_HG_oreder> A_HG_oreder { get; set; }
        public virtual DbSet<Card_BaseInfo> Card_BaseInfo { get; set; }
        public virtual DbSet<Card_Cost> Card_Cost { get; set; }
        public virtual DbSet<Card_CustomField> Card_CustomField { get; set; }
        public virtual DbSet<Card_Detail> Card_Detail { get; set; }
        public virtual DbSet<Card_Discount> Card_Discount { get; set; }
        public virtual DbSet<dt_article> dt_article { get; set; }
        public virtual DbSet<dt_article_albums> dt_article_albums { get; set; }
        public virtual DbSet<dt_article_attach> dt_article_attach { get; set; }
        public virtual DbSet<dt_article_attribute_field> dt_article_attribute_field { get; set; }
        public virtual DbSet<dt_article_attribute_value> dt_article_attribute_value { get; set; }
        public virtual DbSet<dt_article_category> dt_article_category { get; set; }
        public virtual DbSet<dt_article_comment> dt_article_comment { get; set; }
        public virtual DbSet<dt_channel> dt_channel { get; set; }
        public virtual DbSet<dt_channel_category> dt_channel_category { get; set; }
        public virtual DbSet<dt_channel_field> dt_channel_field { get; set; }
        public virtual DbSet<dt_express> dt_express { get; set; }
        public virtual DbSet<dt_feedback> dt_feedback { get; set; }
        public virtual DbSet<dt_link> dt_link { get; set; }
        public virtual DbSet<dt_mail_template> dt_mail_template { get; set; }
        public virtual DbSet<dt_manager> dt_manager { get; set; }
        public virtual DbSet<dt_manager_log> dt_manager_log { get; set; }
        public virtual DbSet<dt_manager_role> dt_manager_role { get; set; }
        public virtual DbSet<dt_manager_role_value> dt_manager_role_value { get; set; }
        public virtual DbSet<dt_navigation> dt_navigation { get; set; }
        public virtual DbSet<dt_order_goods> dt_order_goods { get; set; }
        public virtual DbSet<dt_orders> dt_orders { get; set; }
        public virtual DbSet<dt_payment> dt_payment { get; set; }
        public virtual DbSet<dt_sms_template> dt_sms_template { get; set; }
        public virtual DbSet<dt_user_amount_log> dt_user_amount_log { get; set; }
        public virtual DbSet<dt_user_code> dt_user_code { get; set; }
        public virtual DbSet<dt_user_group_price> dt_user_group_price { get; set; }
        public virtual DbSet<dt_user_groups> dt_user_groups { get; set; }
        public virtual DbSet<dt_user_login_log> dt_user_login_log { get; set; }
        public virtual DbSet<dt_user_message> dt_user_message { get; set; }
        public virtual DbSet<dt_user_oauth> dt_user_oauth { get; set; }
        public virtual DbSet<dt_user_oauth_app> dt_user_oauth_app { get; set; }
        public virtual DbSet<dt_user_point_log> dt_user_point_log { get; set; }
        public virtual DbSet<dt_users> dt_users { get; set; }
        public virtual DbSet<pre_common_district> pre_common_district { get; set; }
        public virtual DbSet<wx_agent_info> wx_agent_info { get; set; }
        public virtual DbSet<wx_albums_info> wx_albums_info { get; set; }
        public virtual DbSet<wx_albums_photo> wx_albums_photo { get; set; }
        public virtual DbSet<wx_albums_sys> wx_albums_sys { get; set; }
        public virtual DbSet<wx_albums_type> wx_albums_type { get; set; }
        public virtual DbSet<wx_book_albums> wx_book_albums { get; set; }
        public virtual DbSet<wx_book_cart> wx_book_cart { get; set; }
        public virtual DbSet<wx_book_catalog> wx_book_catalog { get; set; }
        public virtual DbSet<wx_book_catalog_attribute> wx_book_catalog_attribute { get; set; }
        public virtual DbSet<wx_book_category> wx_book_category { get; set; }
        public virtual DbSet<wx_book_product> wx_book_product { get; set; }
        public virtual DbSet<wx_book_productAttr_value> wx_book_productAttr_value { get; set; }
        public virtual DbSet<wx_book_setting> wx_book_setting { get; set; }
        public virtual DbSet<wx_book_sku> wx_book_sku { get; set; }
        public virtual DbSet<wx_book_templates> wx_book_templates { get; set; }
        public virtual DbSet<wx_book_templates_wcode> wx_book_templates_wcode { get; set; }
        public virtual DbSet<wx_book_user_addr> wx_book_user_addr { get; set; }
        public virtual DbSet<wx_cards> wx_cards { get; set; }
        public virtual DbSet<wx_cards_gl> wx_cards_gl { get; set; }
        public virtual DbSet<wx_dati_base> wx_dati_base { get; set; }
        public virtual DbSet<wx_dati_dx> wx_dati_dx { get; set; }
        public virtual DbSet<wx_dati_user> wx_dati_user { get; set; }
        public virtual DbSet<wx_diancai_blacklist> wx_diancai_blacklist { get; set; }
        public virtual DbSet<wx_diancai_caipin_category> wx_diancai_caipin_category { get; set; }
        public virtual DbSet<wx_diancai_caipin_manage> wx_diancai_caipin_manage { get; set; }
        public virtual DbSet<wx_diancai_desknum> wx_diancai_desknum { get; set; }
        public virtual DbSet<wx_diancai_dianyuan> wx_diancai_dianyuan { get; set; }
        public virtual DbSet<wx_diancai_dingdan_caiping> wx_diancai_dingdan_caiping { get; set; }
        public virtual DbSet<wx_diancai_dingdan_manage> wx_diancai_dingdan_manage { get; set; }
        public virtual DbSet<wx_diancai_form_control> wx_diancai_form_control { get; set; }
        public virtual DbSet<wx_diancai_form_result> wx_diancai_form_result { get; set; }
        public virtual DbSet<wx_diancai_member> wx_diancai_member { get; set; }
        public virtual DbSet<wx_diancai_shop_advertisement> wx_diancai_shop_advertisement { get; set; }
        public virtual DbSet<wx_diancai_shop_setup> wx_diancai_shop_setup { get; set; }
        public virtual DbSet<wx_diancai_shopinfo> wx_diancai_shopinfo { get; set; }
        public virtual DbSet<wx_diancai_shoppic> wx_diancai_shoppic { get; set; }
        public virtual DbSet<wx_dzpActionInfo> wx_dzpActionInfo { get; set; }
        public virtual DbSet<wx_dzpAwardItem> wx_dzpAwardItem { get; set; }
        public virtual DbSet<wx_dzpAwardUser> wx_dzpAwardUser { get; set; }
        public virtual DbSet<wx_dzpUsersTemp> wx_dzpUsersTemp { get; set; }
        public virtual DbSet<wx_ggkActionInfo> wx_ggkActionInfo { get; set; }
        public virtual DbSet<wx_ggkAwardItem> wx_ggkAwardItem { get; set; }
        public virtual DbSet<wx_ggkAwardUser> wx_ggkAwardUser { get; set; }
        public virtual DbSet<wx_ggkUsersTemp> wx_ggkUsersTemp { get; set; }
        public virtual DbSet<wx_lbs_setting> wx_lbs_setting { get; set; }
        public virtual DbSet<wx_lbs_shopInfo> wx_lbs_shopInfo { get; set; }
        public virtual DbSet<wx_link_module> wx_link_module { get; set; }
        public virtual DbSet<wx_logs> wx_logs { get; set; }
        public virtual DbSet<wx_manager_bill> wx_manager_bill { get; set; }
        public virtual DbSet<wx_message_blacklist> wx_message_blacklist { get; set; }
        public virtual DbSet<wx_message_list> wx_message_list { get; set; }
        public virtual DbSet<wx_message_setting> wx_message_setting { get; set; }
        public virtual DbSet<wx_module_templates> wx_module_templates { get; set; }
        public virtual DbSet<wx_module_templates_wcode> wx_module_templates_wcode { get; set; }
        public virtual DbSet<wx_order_temp> wx_order_temp { get; set; }
        public virtual DbSet<wx_pano_jd> wx_pano_jd { get; set; }
        public virtual DbSet<wx_pano_sys> wx_pano_sys { get; set; }
        public virtual DbSet<wx_payment_alipay> wx_payment_alipay { get; set; }
        public virtual DbSet<wx_payment_type> wx_payment_type { get; set; }
        public virtual DbSet<wx_payment_wxpay> wx_payment_wxpay { get; set; }
        public virtual DbSet<wx_PicStore> wx_PicStore { get; set; }
        public virtual DbSet<wx_product> wx_product { get; set; }
        public virtual DbSet<wx_product_comment> wx_product_comment { get; set; }
        public virtual DbSet<wx_product_sys> wx_product_sys { get; set; }
        public virtual DbSet<wx_product_type> wx_product_type { get; set; }
        public virtual DbSet<wx_property_info> wx_property_info { get; set; }
        public virtual DbSet<wx_purchase_base> wx_purchase_base { get; set; }
        public virtual DbSet<wx_purchase_customer> wx_purchase_customer { get; set; }
        public virtual DbSet<wx_requestRule> wx_requestRule { get; set; }
        public virtual DbSet<wx_requestRuleContent> wx_requestRuleContent { get; set; }
        public virtual DbSet<wx_requst_BaseData> wx_requst_BaseData { get; set; }
        public virtual DbSet<wx_response_BaseData> wx_response_BaseData { get; set; }
        public virtual DbSet<wx_shop_albums> wx_shop_albums { get; set; }
        public virtual DbSet<wx_shop_brand> wx_shop_brand { get; set; }
        public virtual DbSet<wx_shop_cart> wx_shop_cart { get; set; }
        public virtual DbSet<wx_shop_catalog> wx_shop_catalog { get; set; }
        public virtual DbSet<wx_shop_catalog_attribute> wx_shop_catalog_attribute { get; set; }
        public virtual DbSet<wx_shop_category> wx_shop_category { get; set; }
        public virtual DbSet<wx_shop_category_catalog> wx_shop_category_catalog { get; set; }
        public virtual DbSet<wx_shop_comment> wx_shop_comment { get; set; }
        public virtual DbSet<wx_shop_product> wx_shop_product { get; set; }
        public virtual DbSet<wx_shop_productAttr_value> wx_shop_productAttr_value { get; set; }
        public virtual DbSet<wx_shop_setting> wx_shop_setting { get; set; }
        public virtual DbSet<wx_shop_sku> wx_shop_sku { get; set; }
        public virtual DbSet<wx_shop_user_addr> wx_shop_user_addr { get; set; }
        public virtual DbSet<wx_sjb_bisai> wx_sjb_bisai { get; set; }
        public virtual DbSet<wx_sjb_jcDetail> wx_sjb_jcDetail { get; set; }
        public virtual DbSet<wx_sjb_qiudui> wx_sjb_qiudui { get; set; }
        public virtual DbSet<wx_sjb_richeng> wx_sjb_richeng { get; set; }
        public virtual DbSet<wx_sjb_users> wx_sjb_users { get; set; }
        public virtual DbSet<wx_small_link> wx_small_link { get; set; }
        public virtual DbSet<wx_sms_config> wx_sms_config { get; set; }
        public virtual DbSet<wx_sms_info> wx_sms_info { get; set; }
        public virtual DbSet<wx_sq_act> wx_sq_act { get; set; }
        public virtual DbSet<wx_sq_heimd> wx_sq_heimd { get; set; }
        public virtual DbSet<wx_sq_piclist> wx_sq_piclist { get; set; }
        public virtual DbSet<wx_sTicket> wx_sTicket { get; set; }
        public virtual DbSet<wx_sttAwardItem> wx_sttAwardItem { get; set; }
        public virtual DbSet<wx_sttAwardUser> wx_sttAwardUser { get; set; }
        public virtual DbSet<wx_sysConfig> wx_sysConfig { get; set; }
        public virtual DbSet<wx_templates> wx_templates { get; set; }
        public virtual DbSet<wx_templates_wcode> wx_templates_wcode { get; set; }
        public virtual DbSet<wx_ucard_adver> wx_ucard_adver { get; set; }
        public virtual DbSet<wx_ucard_cardinfo> wx_ucard_cardinfo { get; set; }
        public virtual DbSet<wx_ucard_gift> wx_ucard_gift { get; set; }
        public virtual DbSet<wx_ucard_notice> wx_ucard_notice { get; set; }
        public virtual DbSet<wx_ucard_privileges> wx_ucard_privileges { get; set; }
        public virtual DbSet<wx_ucard_score> wx_ucard_score { get; set; }
        public virtual DbSet<wx_ucard_store> wx_ucard_store { get; set; }
        public virtual DbSet<wx_ucard_store_fendian> wx_ucard_store_fendian { get; set; }
        public virtual DbSet<wx_ucard_sys> wx_ucard_sys { get; set; }
        public virtual DbSet<wx_ucard_ticket> wx_ucard_ticket { get; set; }
        public virtual DbSet<wx_ucard_udegree> wx_ucard_udegree { get; set; }
        public virtual DbSet<wx_ucard_usercard> wx_ucard_usercard { get; set; }
        public virtual DbSet<wx_ucard_users> wx_ucard_users { get; set; }
        public virtual DbSet<wx_ucard_users_consumeinfo> wx_ucard_users_consumeinfo { get; set; }
        public virtual DbSet<wx_UserGroup> wx_UserGroup { get; set; }
        public virtual DbSet<wx_Userinfo> wx_Userinfo { get; set; }
        public virtual DbSet<wx_userweixin> wx_userweixin { get; set; }
        public virtual DbSet<wx_vote_base> wx_vote_base { get; set; }
        public virtual DbSet<wx_vote_item> wx_vote_item { get; set; }
        public virtual DbSet<wx_vote_result> wx_vote_result { get; set; }
        public virtual DbSet<wx_wifi> wx_wifi { get; set; }
        public virtual DbSet<wx_wsite_modulebase> wx_wsite_modulebase { get; set; }
        public virtual DbSet<wx_wsite_setting> wx_wsite_setting { get; set; }
        public virtual DbSet<wx_xt_base> wx_xt_base { get; set; }
        public virtual DbSet<wx_xt_photo> wx_xt_photo { get; set; }
        public virtual DbSet<wx_xt_user> wx_xt_user { get; set; }
        public virtual DbSet<wx_xt_zhufu> wx_xt_zhufu { get; set; }
        public virtual DbSet<wx_yy_base> wx_yy_base { get; set; }
        public virtual DbSet<wx_yy_control> wx_yy_control { get; set; }
        public virtual DbSet<wx_yy_result> wx_yy_result { get; set; }
        public virtual DbSet<wx_yyyActionInfo> wx_yyyActionInfo { get; set; }
        public virtual DbSet<wx_yyyAwardItem> wx_yyyAwardItem { get; set; }
        public virtual DbSet<wx_yyyAwardUser> wx_yyyAwardUser { get; set; }
        public virtual DbSet<wx_yyyUsersTemp> wx_yyyUsersTemp { get; set; }
        public virtual DbSet<v_wxRuleContent> v_wxRuleContent { get; set; }
        public virtual DbSet<view_agent_list> view_agent_list { get; set; }
        public virtual DbSet<view_channel_bottommenu> view_channel_bottommenu { get; set; }
        public virtual DbSet<view_channel_caseshow> view_channel_caseshow { get; set; }
        public virtual DbSet<view_channel_companyinfo> view_channel_companyinfo { get; set; }
        public virtual DbSet<view_channel_content> view_channel_content { get; set; }
        public virtual DbSet<view_channel_help> view_channel_help { get; set; }
        public virtual DbSet<view_channel_hezuo> view_channel_hezuo { get; set; }
        public virtual DbSet<view_channel_hotnews> view_channel_hotnews { get; set; }
        public virtual DbSet<view_channel_modulebrief> view_channel_modulebrief { get; set; }
        public virtual DbSet<view_channel_news> view_channel_news { get; set; }
        public virtual DbSet<view_channel_pc_pic> view_channel_pc_pic { get; set; }
        public virtual DbSet<view_channel_photo> view_channel_photo { get; set; }
    
        public virtual int p_query_keywords(Nullable<int> wid, string keywords, ObjectParameter id, ObjectParameter responseType, ObjectParameter modelFunctionName, ObjectParameter modelFunctionId)
        {
            var widParameter = wid.HasValue ?
                new ObjectParameter("wid", wid) :
                new ObjectParameter("wid", typeof(int));
    
            var keywordsParameter = keywords != null ?
                new ObjectParameter("keywords", keywords) :
                new ObjectParameter("keywords", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_query_keywords", widParameter, keywordsParameter, id, responseType, modelFunctionName, modelFunctionId);
        }
    
        public virtual int p_ticket(Nullable<int> sid, Nullable<int> uid, Nullable<int> degreeNum, Nullable<decimal> ttcMoney, ObjectParameter ticketidStr)
        {
            var sidParameter = sid.HasValue ?
                new ObjectParameter("sid", sid) :
                new ObjectParameter("sid", typeof(int));
    
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var degreeNumParameter = degreeNum.HasValue ?
                new ObjectParameter("degreeNum", degreeNum) :
                new ObjectParameter("degreeNum", typeof(int));
    
            var ttcMoneyParameter = ttcMoney.HasValue ?
                new ObjectParameter("ttcMoney", ttcMoney) :
                new ObjectParameter("ttcMoney", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_ticket", sidParameter, uidParameter, degreeNumParameter, ttcMoneyParameter, ticketidStr);
        }
    
        public virtual ObjectResult<p_wcode_wsiteinfo_Result> p_wcode_wsiteinfo(Nullable<int> wid)
        {
            var widParameter = wid.HasValue ?
                new ObjectParameter("wid", wid) :
                new ObjectParameter("wid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_wcode_wsiteinfo_Result>("p_wcode_wsiteinfo", widParameter);
        }
    
        public virtual int p_yuyue(Nullable<int> formid)
        {
            var formidParameter = formid.HasValue ?
                new ObjectParameter("formid", formid) :
                new ObjectParameter("formid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_yuyue", formidParameter);
        }
    }
}
