//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_users
    {
        public dt_users()
        {
            this.dt_user_code = new HashSet<dt_user_code>();
            this.dt_user_login_log = new HashSet<dt_user_login_log>();
        }
    
        public int id { get; set; }
        public int group_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string email { get; set; }
        public string nick_name { get; set; }
        public string avatar { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string telphone { get; set; }
        public string mobile { get; set; }
        public string qq { get; set; }
        public string address { get; set; }
        public string safe_question { get; set; }
        public string safe_answer { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> point { get; set; }
        public Nullable<int> exp { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<System.DateTime> reg_time { get; set; }
        public string reg_ip { get; set; }
        public Nullable<byte> isweixin { get; set; }
        public Nullable<int> wid { get; set; }
        public string wxOpenId { get; set; }
        public string wxName { get; set; }
    
        public virtual ICollection<dt_user_code> dt_user_code { get; set; }
        public virtual dt_user_groups dt_user_groups { get; set; }
        public virtual ICollection<dt_user_login_log> dt_user_login_log { get; set; }
    }
}
