//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wxRuleContent
    {
        public int id { get; set; }
        public Nullable<int> wId { get; set; }
        public Nullable<int> uId { get; set; }
        public string ruleName { get; set; }
        public string reqKeywords { get; set; }
        public Nullable<int> reqestType { get; set; }
        public Nullable<int> responseType { get; set; }
        public Nullable<bool> isDefault { get; set; }
        public string modelFunctionName { get; set; }
        public Nullable<int> modelFunctionId { get; set; }
        public Nullable<int> seq { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string agentUrl { get; set; }
        public string agentToken { get; set; }
        public Nullable<bool> isLikeSearch { get; set; }
        public Nullable<int> extInt { get; set; }
        public Nullable<int> extInt2 { get; set; }
        public string extStr { get; set; }
        public string extStr2 { get; set; }
        public string extStr3 { get; set; }
        public string extStr4 { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<int> rId { get; set; }
        public string rContent { get; set; }
        public string rContent2 { get; set; }
        public string detailUrl { get; set; }
        public string picUrl { get; set; }
        public string mediaUrl { get; set; }
        public string meidaHDUrl { get; set; }
        public Nullable<int> cseq { get; set; }
    }
}
