//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_agent_list
    {
        public int id { get; set; }
        public int role_id { get; set; }
        public Nullable<int> role_type { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string real_name { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<int> is_lock { get; set; }
        public string companyName { get; set; }
        public string companyInfo { get; set; }
        public Nullable<int> agentPrice { get; set; }
        public Nullable<int> agentPrice2 { get; set; }
        public Nullable<int> sqJine { get; set; }
        public Nullable<int> czTotMoney { get; set; }
        public Nullable<int> remainMony { get; set; }
        public Nullable<int> userNum { get; set; }
        public Nullable<int> wcodeNum { get; set; }
        public Nullable<int> agentType { get; set; }
        public string agentLevel { get; set; }
        public string industry { get; set; }
        public string agentArea { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public string aRemark { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string qq { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string county { get; set; }
    }
}
