//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_agent_info
    {
        public int id { get; set; }
        public Nullable<int> managerId { get; set; }
        public string companyName { get; set; }
        public string companyInfo { get; set; }
        public Nullable<int> agentPrice { get; set; }
        public Nullable<int> agentPrice2 { get; set; }
        public Nullable<int> sqJine { get; set; }
        public Nullable<int> czTotMoney { get; set; }
        public Nullable<int> remainMony { get; set; }
        public Nullable<int> userNum { get; set; }
        public Nullable<int> wcodeNum { get; set; }
        public Nullable<int> agentType { get; set; }
        public string agentLevel { get; set; }
        public string industry { get; set; }
        public string agentArea { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public string aRemark { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
