//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_albums_photo
    {
        public int id { get; set; }
        public Nullable<int> aId { get; set; }
        public string pName { get; set; }
        public string photoPic { get; set; }
        public string pContent { get; set; }
        public Nullable<int> seq { get; set; }
        public Nullable<bool> isHidden { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string createPerson { get; set; }
    }
}
