//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_albums_type
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string typeName { get; set; }
        public string bannerPic { get; set; }
        public string typeIco { get; set; }
        public string typePic { get; set; }
        public string tContent { get; set; }
        public string remark { get; set; }
        public string music { get; set; }
        public Nullable<int> showType { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> sort_id { get; set; }
    }
}
