//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_albums_info
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string aName { get; set; }
        public string facePic { get; set; }
        public string aContent { get; set; }
        public Nullable<bool> showContent { get; set; }
        public Nullable<bool> isHidden { get; set; }
        public Nullable<int> seq { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string createPerson { get; set; }
        public Nullable<int> typeId { get; set; }
        public string music { get; set; }
        public Nullable<int> showType { get; set; }
    }
}
