//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_book_cart
    {
        public int id { get; set; }
        public string openid { get; set; }
        public int wid { get; set; }
        public int productId { get; set; }
        public int skuId { get; set; }
        public string skuInfo { get; set; }
        public double totPrice { get; set; }
        public int productNum { get; set; }
        public System.DateTime createDate { get; set; }
    }
}
