//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_book_setting
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string bookName { get; set; }
        public string copyright { get; set; }
        public string logo { get; set; }
        public string bgPic { get; set; }
        public string tel { get; set; }
        public string addr { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> extInt { get; set; }
        public string extStr { get; set; }
    }
}
