//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_cards
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string openid { get; set; }
        public string title { get; set; }
        public string backPic { get; set; }
        public string backMusic { get; set; }
        public string backCartoon { get; set; }
        public string characters { get; set; }
        public string copyRight { get; set; }
        public string buttonCharacter { get; set; }
        public Nullable<bool> display { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<int> ckCount { get; set; }
        public Nullable<int> zfCount { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
