//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_diancai_shopinfo
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string hotelName { get; set; }
        public string hotelLogo { get; set; }
        public Nullable<System.DateTime> hoteltimeBegin { get; set; }
        public Nullable<System.DateTime> hoteltimeEnd { get; set; }
        public Nullable<bool> limiteOrder { get; set; }
        public string dcRename { get; set; }
        public Nullable<double> sendPrice { get; set; }
        public Nullable<double> sendCost { get; set; }
        public Nullable<int> freeSendcost { get; set; }
        public string radius { get; set; }
        public string sendArea { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public Nullable<int> personLimite { get; set; }
        public string notice { get; set; }
        public string hotelintroduction { get; set; }
        public string email { get; set; }
        public string emailpwd { get; set; }
        public string stmp { get; set; }
        public string css { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string kcType { get; set; }
        public string miaoshu { get; set; }
        public Nullable<double> xplace { get; set; }
        public Nullable<double> yplace { get; set; }
        public Nullable<System.DateTime> hoteltimeBegin1 { get; set; }
        public Nullable<System.DateTime> hoteltimeEnd1 { get; set; }
        public Nullable<System.DateTime> hoteltimeBegin2 { get; set; }
        public Nullable<System.DateTime> hoteltimeEnd2 { get; set; }
    }
}
