//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_dati_dx
    {
        public int id { get; set; }
        public Nullable<int> sid { get; set; }
        public int pid { get; set; }
        public string title { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<bool> isshow { get; set; }
        public string answer { get; set; }
        public string summary { get; set; }
        public string xA { get; set; }
        public string xB { get; set; }
        public string xC { get; set; }
        public string xD { get; set; }
        public string xE { get; set; }
        public string xF { get; set; }
    }
}
