//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_diancai_member
    {
        public int id { get; set; }
        public Nullable<int> shopid { get; set; }
        public string Name { get; set; }
        public string openid { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string weixinName { get; set; }
        public string memberName { get; set; }
        public string menberTel { get; set; }
        public string memberAddress { get; set; }
        public Nullable<int> successDingdan { get; set; }
        public Nullable<int> failDingdan { get; set; }
        public Nullable<int> cancelDingdan { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> zongjifen { get; set; }
        public Nullable<double> zongcje { get; set; }
    }
}
