//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_diancai_form_control
    {
        public int id { get; set; }
        public Nullable<int> shopinfoId { get; set; }
        public string cName { get; set; }
        public string cType { get; set; }
        public Nullable<int> minLength { get; set; }
        public Nullable<int> maxLength { get; set; }
        public string defaultValue { get; set; }
        public Nullable<bool> isBiTian { get; set; }
        public Nullable<int> seq { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string remark { get; set; }
        public Nullable<int> extInt { get; set; }
        public string extStr { get; set; }
        public Nullable<bool> isSys { get; set; }
        public string sysControlerType { get; set; }
    }
}
