//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_dati_base
    {
        public int id { get; set; }
        public int wid { get; set; }
        public string title { get; set; }
        public string bjcolor { get; set; }
        public string headimg { get; set; }
        public string summary { get; set; }
        public Nullable<int> dttime { get; set; }
        public Nullable<bool> isshowend { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string dxtitle { get; set; }
        public Nullable<int> dxgetnum { get; set; }
        public Nullable<int> dxscore { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<int> jftype { get; set; }
        public Nullable<int> jfval { get; set; }
    }
}
