//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_diancai_dianyuan
    {
        public int id { get; set; }
        public Nullable<int> shopid { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string bianhao { get; set; }
        public string dianyuanName { get; set; }
        public string dianyuanTel { get; set; }
        public string userName { get; set; }
        public string pwd { get; set; }
        public Nullable<int> userStatus { get; set; }
        public string fendian { get; set; }
        public Nullable<System.DateTime> beginTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public string remark { get; set; }
    }
}
