//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_ggkAwardItem
    {
        public int id { get; set; }
        public Nullable<int> actId { get; set; }
        public string jxName { get; set; }
        public string jpName { get; set; }
        public Nullable<int> jpNum { get; set; }
        public Nullable<int> jpRealNum { get; set; }
        public Nullable<int> sort_id { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
