//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_logs
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string modelName { get; set; }
        public string remark { get; set; }
        public Nullable<int> logsType { get; set; }
        public string logsTypeName { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string logsContent { get; set; }
        public string logsTitle { get; set; }
        public string funName { get; set; }
        public string createPerson { get; set; }
        public Nullable<int> extInt { get; set; }
        public string extStr { get; set; }
        public string extStr2 { get; set; }
        public string extStr3 { get; set; }
        public string flg { get; set; }
        public string flg2 { get; set; }
        public string flg3 { get; set; }
        public Nullable<int> flgInt { get; set; }
        public Nullable<System.DateTime> flgDate { get; set; }
    }
}
