//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_link_module
    {
        public int id { get; set; }
        public string lName { get; set; }
        public string moduleName { get; set; }
        public string moduleCode { get; set; }
        public Nullable<int> moduleType { get; set; }
        public string urlRule { get; set; }
        public Nullable<bool> urlNeedReplace { get; set; }
        public string tableName { get; set; }
        public Nullable<bool> isGlobal { get; set; }
        public Nullable<bool> isMore { get; set; }
        public Nullable<int> sortId { get; set; }
        public string remark { get; set; }
        public string idColumn { get; set; }
        public string nameColumn { get; set; }
    }
}
