//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_lbs_shopInfo
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string shopName { get; set; }
        public string telphone { get; set; }
        public string brief { get; set; }
        public string shopContent { get; set; }
        public string shopLogo { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string detailAddr { get; set; }
        public Nullable<double> xPoint { get; set; }
        public Nullable<double> yPoint { get; set; }
        public string wUrl { get; set; }
        public Nullable<int> seq { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
