//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_module_templates
    {
        public int id { get; set; }
        public string tName { get; set; }
        public string author { get; set; }
        public string moduleName { get; set; }
        public string moduleCode { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string version { get; set; }
        public string forWxVersion { get; set; }
        public string typeName { get; set; }
        public Nullable<int> typeId { get; set; }
        public string aboutPic { get; set; }
        public string tFileName { get; set; }
        public string degreeName { get; set; }
        public Nullable<int> degreId { get; set; }
        public string remark { get; set; }
    }
}
