//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_module_templates_wcode
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public Nullable<int> tid { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> extInt { get; set; }
        public string extStr { get; set; }
        public string extStr2 { get; set; }
        public Nullable<int> listTid { get; set; }
        public Nullable<int> detailTid { get; set; }
        public string bmenuTid { get; set; }
        public Nullable<int> channelTid { get; set; }
        public Nullable<int> topcolorTypeId { get; set; }
        public string topcolorTypeName { get; set; }
        public string topcolorHtml { get; set; }
    }
}
