//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_manager_bill
    {
        public int id { get; set; }
        public Nullable<int> managerId { get; set; }
        public string moneyType { get; set; }
        public Nullable<int> billMoney { get; set; }
        public string billUsed { get; set; }
        public Nullable<int> operPersonId { get; set; }
        public Nullable<System.DateTime> operDate { get; set; }
        public string remark { get; set; }
    }
}
