//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_order_temp
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string openid { get; set; }
        public string uName { get; set; }
        public Nullable<int> personNum { get; set; }
        public Nullable<int> stadId { get; set; }
        public string stadName { get; set; }
        public Nullable<int> roomId { get; set; }
        public string roomName { get; set; }
        public Nullable<int> rtimesId { get; set; }
        public Nullable<System.DateTime> ydBeginDate { get; set; }
        public Nullable<System.DateTime> ydEndDate { get; set; }
        public string out_trade_no { get; set; }
        public string ordersubject { get; set; }
        public Nullable<double> orderMoney { get; set; }
        public Nullable<int> orderStatus { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> complateDate { get; set; }
        public string phone { get; set; }
        public Nullable<int> extInt { get; set; }
        public Nullable<double> extFloat { get; set; }
        public string extStr { get; set; }
        public string extStr2 { get; set; }
        public Nullable<double> ttPrice { get; set; }
    }
}
