//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_product
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string hdName { get; set; }
        public string pSubject { get; set; }
        public Nullable<int> typeId { get; set; }
        public Nullable<System.DateTime> beginDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string addr { get; set; }
        public string pContent { get; set; }
        public Nullable<int> minPersonNum { get; set; }
        public Nullable<int> maxPersonNum { get; set; }
        public string personContent { get; set; }
        public Nullable<bool> isOpen { get; set; }
        public string createPerson { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string url { get; set; }
        public string urlName { get; set; }
        public string btnName { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<bool> showPrice { get; set; }
        public Nullable<bool> showYuDing { get; set; }
        public Nullable<bool> showDate { get; set; }
        public Nullable<int> extInt { get; set; }
        public string extStr { get; set; }
        public string extStr2 { get; set; }
        public string extStr3 { get; set; }
        public string tel { get; set; }
        public string daohangurl { get; set; }
    }
}
