//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_property_info
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public Nullable<int> typeId { get; set; }
        public string typeName { get; set; }
        public string iName { get; set; }
        public string iContent { get; set; }
        public Nullable<int> expires_in { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string categoryName { get; set; }
        public string remark { get; set; }
    }
}
