//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_product_type
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public Nullable<int> parentId { get; set; }
        public string tCode { get; set; }
        public string tName { get; set; }
        public string tUrl { get; set; }
        public Nullable<int> class_layer { get; set; }
        public string remark { get; set; }
        public string icoPic { get; set; }
        public Nullable<int> sort_id { get; set; }
        public Nullable<System.DateTime> creatDate { get; set; }
        public string extStr { get; set; }
        public string extStr2 { get; set; }
        public Nullable<int> store_id { get; set; }
        public string tel { get; set; }
        public string daohangurl { get; set; }
        public Nullable<bool> showDefault { get; set; }
    }
}
