//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_payment_alipay
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string ownerName { get; set; }
        public string partner { get; set; }
        public string e_key { get; set; }
        public string private_key { get; set; }
        public string public_key { get; set; }
        public string sign_type { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> extInt { get; set; }
        public string extStr { get; set; }
        public string extStr2 { get; set; }
    }
}
