//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_purchase_customer
    {
        public int Id { get; set; }
        public Nullable<int> baseid { get; set; }
        public string sn { get; set; }
        public string customerName { get; set; }
        public Nullable<int> customerNum { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> dateJoin { get; set; }
        public Nullable<System.DateTime> dateUse { get; set; }
        public Nullable<System.DateTime> craeteTime { get; set; }
        public string openid { get; set; }
        public string Remark { get; set; }
    }
}
