//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_pano_jd
    {
        public int id { get; set; }
        public Nullable<int> sysId { get; set; }
        public Nullable<int> wid { get; set; }
        public string jdName { get; set; }
        public string music { get; set; }
        public string pic_front { get; set; }
        public string pic_right { get; set; }
        public string pic_behind { get; set; }
        public string pic_left { get; set; }
        public string pic_top { get; set; }
        public string pic_bottom { get; set; }
        public string pic_yulan { get; set; }
        public string remark { get; set; }
        public Nullable<int> seq { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string extStr { get; set; }
        public string extStr2 { get; set; }
    }
}
