//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_purchase_base
    {
        public int Id { get; set; }
        public string activityName { get; set; }
        public string activitySummary { get; set; }
        public Nullable<System.DateTime> activityTimebegin { get; set; }
        public string email { get; set; }
        public string emailPwd { get; set; }
        public string smtp { get; set; }
        public string shopsPwd { get; set; }
        public string activeDescription { get; set; }
        public string specialRemind { get; set; }
        public string activityEndtitle { get; set; }
        public string endExplanation { get; set; }
        public string shopstel { get; set; }
        public string address { get; set; }
        public string introduction { get; set; }
        public string goodName { get; set; }
        public Nullable<double> costPrice { get; set; }
        public Nullable<int> limitCount { get; set; }
        public Nullable<double> groupPrice { get; set; }
        public Nullable<int> totalCount { get; set; }
        public Nullable<int> groupPerson { get; set; }
        public Nullable<int> virtualPerson { get; set; }
        public string copyrightSetup { get; set; }
        public Nullable<System.DateTime> activityTimeend { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> wid { get; set; }
        public string imageUrl { get; set; }
        public string imageUrlend { get; set; }
        public Nullable<double> txtLatXPoint { get; set; }
        public Nullable<double> txtLngYPoint { get; set; }
    }
}
