//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_PicStore
    {
        public int id { get; set; }
        public string picName { get; set; }
        public string picUri { get; set; }
        public string picTemplates { get; set; }
        public Nullable<int> picType { get; set; }
        public string picUsedType { get; set; }
        public string picValue { get; set; }
        public string picCreatePerson { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
