//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_payment_wxpay
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string partnerId { get; set; }
        public string appId { get; set; }
        public string partnerKey { get; set; }
        public string paySignKey { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string CertInfoPath { get; set; }
        public string partnerPwd { get; set; }
        public string shName { get; set; }
        public string bankName { get; set; }
        public string bankCode { get; set; }
        public string remark { get; set; }
        public Nullable<bool> quicklyFH { get; set; }
    }
}
