//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_product_comment
    {
        public int id { get; set; }
        public Nullable<int> hdId { get; set; }
        public string openId { get; set; }
        public string commentContent { get; set; }
        public Nullable<int> commentType { get; set; }
        public string commentRemark { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> replyStatus { get; set; }
        public string replyPerson { get; set; }
        public string replyContent { get; set; }
        public Nullable<System.DateTime> replyDate { get; set; }
    }
}
