//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_response_BaseData
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string wx_openid { get; set; }
        public string requestType { get; set; }
        public string requestContent { get; set; }
        public string responseType { get; set; }
        public string reponseContent { get; set; }
        public string createTime { get; set; }
        public string wx_xmlContent { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> flag { get; set; }
        public string rType { get; set; }
        public string remark { get; set; }
        public Nullable<int> extInt { get; set; }
        public string extStr { get; set; }
        public string extStr2 { get; set; }
        public string extStr3 { get; set; }
    }
}
