//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_requestRuleContent
    {
        public int id { get; set; }
        public Nullable<int> uId { get; set; }
        public Nullable<int> rId { get; set; }
        public string rContent { get; set; }
        public string rContent2 { get; set; }
        public string detailUrl { get; set; }
        public string picUrl { get; set; }
        public string mediaUrl { get; set; }
        public string meidaHDUrl { get; set; }
        public string remark { get; set; }
        public Nullable<int> seq { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> extInt { get; set; }
        public Nullable<int> extInt2 { get; set; }
        public string extStr { get; set; }
        public string extStr2 { get; set; }
        public string extstr3 { get; set; }
    }
}
