//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_sq_act
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public Nullable<bool> isOpen { get; set; }
        public string actName { get; set; }
        public string brief { get; set; }
        public Nullable<bool> shenghe { get; set; }
        public string noshengheTip { get; set; }
        public string shengheTip { get; set; }
        public string bannerPic { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<System.DateTime> beginDate { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> sort_id { get; set; }
    }
}
