//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_shop_sku
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }
        public string sku { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<double> price { get; set; }
        public string attributeValue { get; set; }
        public Nullable<int> attributeId { get; set; }
    }
}
