//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_sjb_bisai
    {
        public int id { get; set; }
        public string bsPic { get; set; }
        public string bsRemark { get; set; }
        public Nullable<int> rcId { get; set; }
        public Nullable<int> qd1Id { get; set; }
        public Nullable<int> qd2Id { get; set; }
        public Nullable<System.DateTime> beginDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<System.DateTime> jcBeginDate { get; set; }
        public Nullable<System.DateTime> jcEndDate { get; set; }
        public Nullable<int> resultType { get; set; }
        public Nullable<int> rType1Times { get; set; }
        public Nullable<int> rType2Times { get; set; }
        public Nullable<int> rType3Times { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
