//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_shop_product
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> catalogId { get; set; }
        public Nullable<int> brandId { get; set; }
        public string sku { get; set; }
        public string productName { get; set; }
        public string shortDesc { get; set; }
        public string unit { get; set; }
        public Nullable<double> weight { get; set; }
        public string description { get; set; }
        public string seo_title { get; set; }
        public string seo_keywords { get; set; }
        public string seo_description { get; set; }
        public string focusImgUrl { get; set; }
        public string thumbnailsUrll { get; set; }
        public Nullable<bool> recommended { get; set; }
        public Nullable<bool> latest { get; set; }
        public Nullable<bool> hotsale { get; set; }
        public Nullable<bool> specialOffer { get; set; }
        public Nullable<double> costPrice { get; set; }
        public Nullable<double> marketPrice { get; set; }
        public Nullable<double> salePrice { get; set; }
        public Nullable<bool> upselling { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<System.DateTime> addDate { get; set; }
        public Nullable<int> vistiCounts { get; set; }
        public Nullable<int> sort_id { get; set; }
        public Nullable<System.DateTime> productionDate { get; set; }
        public Nullable<System.DateTime> ExpiryEndDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    }
}
