//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_small_link
    {
        public int id { get; set; }
        public string sName { get; set; }
        public string url { get; set; }
        public string sType { get; set; }
        public Nullable<int> sortId { get; set; }
        public Nullable<bool> isGlobal { get; set; }
        public string companyName { get; set; }
        public string comTel { get; set; }
        public string remark { get; set; }
    }
}
