//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_shop_brand
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string bName { get; set; }
        public string logo { get; set; }
        public string companyUrl { get; set; }
        public string companyName { get; set; }
        public string remark { get; set; }
        public Nullable<int> sort_id { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
