//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_sms_config
    {
        public int id { get; set; }
        public int wid { get; set; }
        public string uName { get; set; }
        public string ucode { get; set; }
        public string pwd { get; set; }
        public string qianming { get; set; }
        public System.DateTime createDate { get; set; }
        public string remark { get; set; }
        public Nullable<int> sortId { get; set; }
    }
}
