//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_sTicket
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string actionName { get; set; }
        public string succTip { get; set; }
        public string brief { get; set; }
        public Nullable<System.DateTime> beginDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string aContent { get; set; }
        public string usedRemark { get; set; }
        public string telphone { get; set; }
        public string wUrl { get; set; }
        public Nullable<int> seq { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string endNotice { get; set; }
        public string endContent { get; set; }
        public string bannerPic { get; set; }
        public string beginPic { get; set; }
        public string endPic { get; set; }
        public string pwd { get; set; }
    }
}
