//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_shop_comment
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }
        public string openid { get; set; }
        public string user_name { get; set; }
        public string user_ip { get; set; }
        public string cContent { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<int> is_reply { get; set; }
        public string reply_content { get; set; }
        public Nullable<System.DateTime> reply_time { get; set; }
    }
}
