//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_ucard_users
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public Nullable<int> sid { get; set; }
        public string openid { get; set; }
        public string wxName { get; set; }
        public string realName { get; set; }
        public Nullable<int> subscribe { get; set; }
        public string language { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string country { get; set; }
        public string headimgul { get; set; }
        public Nullable<System.DateTime> subscribe_time { get; set; }
        public Nullable<System.DateTime> unsubscribe_time { get; set; }
        public Nullable<int> groupid { get; set; }
        public string groupname { get; set; }
        public string cardNo { get; set; }
        public string pwd { get; set; }
        public Nullable<int> degreeId { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> age { get; set; }
        public string qq { get; set; }
        public string telphone { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string addr { get; set; }
        public Nullable<System.DateTime> regTime { get; set; }
        public string regIp { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> ttScore { get; set; }
        public Nullable<int> qdScore { get; set; }
        public Nullable<int> consumeScore { get; set; }
        public Nullable<double> consumeMoney { get; set; }
    }
}
