//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_ucard_store
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string storeName { get; set; }
        public string logo { get; set; }
        public string storeCatagory { get; set; }
        public string cardBrief { get; set; }
        public string consumePwd { get; set; }
        public string tel { get; set; }
        public string addr { get; set; }
        public Nullable<double> xPoint { get; set; }
        public Nullable<double> yPoint { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> sort_id { get; set; }
        public Nullable<bool> isRecommend { get; set; }
        public string hfPic { get; set; }
    }
}
