//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_ucard_sys
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string tradeTel { get; set; }
        public string tradeContent { get; set; }
        public Nullable<int> cardType { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
