//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_ucard_cardinfo
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string cardName { get; set; }
        public string cardNameColor { get; set; }
        public string logo { get; set; }
        public Nullable<bool> isLogoShow { get; set; }
        public Nullable<int> bgTypeId { get; set; }
        public string bgTypeUrl { get; set; }
        public string bgUrl { get; set; }
        public string cardNoColor { get; set; }
        public string indexTip { get; set; }
        public string noticePic { get; set; }
        public string privilegesPic { get; set; }
        public string qiandaoPic { get; set; }
        public string shopingPic { get; set; }
        public string perinfoPic { get; set; }
        public string instructionsPic { get; set; }
        public string contactusPic { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> sId { get; set; }
    }
}
