//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_userweixin
    {
        public int id { get; set; }
        public Nullable<int> uId { get; set; }
        public string wxName { get; set; }
        public string wxId { get; set; }
        public string yixinId { get; set; }
        public string weixinCode { get; set; }
        public string wxPwd { get; set; }
        public string headerpic { get; set; }
        public string apiurl { get; set; }
        public string wxToken { get; set; }
        public string wxProvince { get; set; }
        public string wxCity { get; set; }
        public string AppId { get; set; }
        public string AppSecret { get; set; }
        public string Access_Token { get; set; }
        public string openIdStr { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> wenziMaxNum { get; set; }
        public Nullable<int> tuwenMaxNum { get; set; }
        public Nullable<int> yuyinMaxNum { get; set; }
        public Nullable<int> wenziDefineNum { get; set; }
        public Nullable<int> tuwenDefineNum { get; set; }
        public Nullable<int> yuyinDefineNum { get; set; }
        public Nullable<int> requestTTNum { get; set; }
        public Nullable<int> requestUsedNum { get; set; }
        public Nullable<int> smsTTNum { get; set; }
        public Nullable<int> smsUsedNum { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<System.DateTime> deleteDate { get; set; }
        public Nullable<int> wxType { get; set; }
        public string remark { get; set; }
        public Nullable<int> seq { get; set; }
        public string extStr { get; set; }
        public string extStr2 { get; set; }
        public string extStr3 { get; set; }
        public Nullable<int> extInt { get; set; }
        public Nullable<int> extInt2 { get; set; }
    }
}
