//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_Userinfo
    {
        public int id { get; set; }
        public int wid { get; set; }
        public string gid { get; set; }
        public string openid { get; set; }
        public int subscribe { get; set; }
        public string nickname { get; set; }
        public Nullable<int> sex { get; set; }
        public string language { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string country { get; set; }
        public string headimgul { get; set; }
        public Nullable<System.DateTime> subscribe_time { get; set; }
        public Nullable<System.DateTime> unsubscribe_time { get; set; }
        public string remark { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> groupid { get; set; }
        public string groupname { get; set; }
        public Nullable<int> extInt { get; set; }
        public string extStr1 { get; set; }
        public string extStr2 { get; set; }
        public string extStr3 { get; set; }
    }
}
