//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_ucard_udegree
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public Nullable<int> degreeNum { get; set; }
        public string callName { get; set; }
        public Nullable<int> score_min { get; set; }
        public Nullable<int> score_max { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> sId { get; set; }
    }
}
