//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_ucard_users_consumeinfo
    {
        public int id { get; set; }
        public Nullable<int> sId { get; set; }
        public Nullable<int> uid { get; set; }
        public string moduleType { get; set; }
        public Nullable<int> moduleTypeId { get; set; }
        public string moduleActionName { get; set; }
        public Nullable<int> moduleActionId { get; set; }
        public Nullable<int> cScoreType { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> cMoneyType { get; set; }
        public Nullable<double> consumeMoney { get; set; }
        public string cContent { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
        public Nullable<int> sort_id { get; set; }
        public string sn { get; set; }
        public string operName { get; set; }
        public string pwd { get; set; }
    }
}
