//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_vote_base
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string title { get; set; }
        public string votepic { get; set; }
        public Nullable<bool> picdisplay { get; set; }
        public string votecontent { get; set; }
        public Nullable<bool> isRadio { get; set; }
        public Nullable<System.DateTime> beginTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<int> resultShowtype { get; set; }
        public string actUrl { get; set; }
        public Nullable<int> voteType { get; set; }
        public Nullable<int> sort_id { get; set; }
        public Nullable<System.DateTime> creatDate { get; set; }
    }
}
