//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_vote_item
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> sort_id { get; set; }
        public string pic_url { get; set; }
        public string pic_jump { get; set; }
        public Nullable<int> sid { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> baseid { get; set; }
        public Nullable<int> tpTimes { get; set; }
    }
}
