//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_wifi
    {
        public int id { get; set; }
        public int wid { get; set; }
        public string appkey { get; set; }
        public string secret { get; set; }
        public string merchantId { get; set; }
        public string extStr { get; set; }
        public string extSt2 { get; set; }
        public string extStr3 { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
