//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_wsite_modulebase
    {
        public int id { get; set; }
        public string mName { get; set; }
        public string mCode { get; set; }
        public Nullable<int> mValueInt { get; set; }
        public string mValue { get; set; }
        public string mType { get; set; }
        public string mTypeName { get; set; }
        public string picUrl { get; set; }
        public string remark { get; set; }
        public Nullable<int> seq { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
