//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_wsite_setting
    {
        public int id { get; set; }
        public Nullable<int> wId { get; set; }
        public string wName { get; set; }
        public string companyName { get; set; }
        public string bgMusic { get; set; }
        public string bgPic { get; set; }
        public Nullable<int> bgDongHuaId { get; set; }
        public string wCopyright { get; set; }
        public string wBrief { get; set; }
        public string remark { get; set; }
        public string phone { get; set; }
        public string addr { get; set; }
        public string addrUrl { get; set; }
        public string email { get; set; }
        public string seo_title { get; set; }
        public string seo_keywords { get; set; }
        public string seo_desc { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> extInt { get; set; }
        public string extStr { get; set; }
        public string extStr2 { get; set; }
    }
}
