//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_xt_base
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string wxTitle { get; set; }
        public string keywords { get; set; }
        public string fengmian { get; set; }
        public string donghua { get; set; }
        public string donghuaSlt { get; set; }
        public string manName { get; set; }
        public string felmanName { get; set; }
        public Nullable<int> nameSeq { get; set; }
        public string tel { get; set; }
        public Nullable<System.DateTime> statedate { get; set; }
        public string addr { get; set; }
        public Nullable<double> lngX { get; set; }
        public Nullable<double> latY { get; set; }
        public string video { get; set; }
        public string video2 { get; set; }
        public string music { get; set; }
        public string word { get; set; }
        public string sqrurl { get; set; }
        public string copyrite { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> templateId { get; set; }
        public string templateName { get; set; }
        public string pwd { get; set; }
        public string extStr { get; set; }
        public string extStr2 { get; set; }
        public Nullable<int> extInt { get; set; }
    }
}
