//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_yy_base
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string title { get; set; }
        public string addr { get; set; }
        public string phone { get; set; }
        public string kfName { get; set; }
        public string content { get; set; }
        public string picUrl { get; set; }
        public Nullable<System.DateTime> beginDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string remark { get; set; }
        public Nullable<int> extInt { get; set; }
        public string extStr { get; set; }
        public string extStr2 { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> seq { get; set; }
        public Nullable<bool> needSMS { get; set; }
    }
}
