//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_yyyActionInfo
    {
        public int id { get; set; }
        public Nullable<int> wid { get; set; }
        public string actName { get; set; }
        public Nullable<System.DateTime> beginDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string brief { get; set; }
        public string contractInfo { get; set; }
        public string actContent { get; set; }
        public string cfcjhf { get; set; }
        public string endNotice { get; set; }
        public string endContent { get; set; }
        public Nullable<int> personNum { get; set; }
        public Nullable<int> personMaxTimes { get; set; }
        public Nullable<int> dayMaxTimes { get; set; }
        public string openXyj { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string beginPic { get; set; }
        public string endPic { get; set; }
        public Nullable<int> aStatus { get; set; }
        public string djPwd { get; set; }
    }
}
